### ISSUE TITLE
Auto Suggest not working

### ISSUE THREAD

**Issue by mitchngwen** [ItemsAdder/ia-vscode#15]
AUTO SUGGEST is not working with this extension anymore. Let me know what you need , and how to get it.

**Comment by LoneDev6** [comment]
You might have to trust the project in order to get autocompletition.
https://code.visualstudio.com/docs/editor/workspace-trust

![image](https://github.com/ItemsAdder/ia-vscode/assets/27242001/4ca7808c-6c8b-4ce9-8833-8e243ae9b2bf)
![image](https://github.com/ItemsAdder/ia-vscode/assets/27242001/0c04f41b-f970-45f7-886a-193031d7b856)
